# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.cache/wt [current_project]
set_property parent.project_path C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/msa.azzazy.AUC/single_cycle/single_cycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Mux_2by1.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/FullAdder.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/DFlipFlop.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/RippleCarryAdder.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Register.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Or.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Decoder_5by32.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/And.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/ShiftLeft_1.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/RegisterFile.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Mux_2by1_32.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/InstMem.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/ImmGen.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/DataMem.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/ControlUnit.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/ALU_ControlUnit.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/ALU.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/DataPath.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Four_Digit.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/DataPath_Demo.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/consts.xdc
set_property used_in_implementation false [get_files C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/consts.xdc]


synth_design -top DataPath_Demo -part xc7a100tcsg324-1


write_checkpoint -force -noxdef DataPath_Demo.dcp

catch { report_utilization -file DataPath_Demo_utilization_synth.rpt -pb DataPath_Demo_utilization_synth.pb }
