# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.cache/wt [current_project]
set_property parent.project_path C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/msa.azzazy.AUC/single_cycle/single_cycle.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/FullAdder.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/RCA.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/Four_Digit.v
  C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/sources_1/new/RCA_Demo.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/consts.xdc
set_property used_in_implementation false [get_files C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/consts.xdc]

read_xdc C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/inv_consts.xdc
set_property used_in_implementation false [get_files C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/inv_consts.xdc]

read_xdc C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/ssd_consts.xdc
set_property used_in_implementation false [get_files C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/ssd_consts.xdc]

read_xdc C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/rca_consts.xdc
set_property used_in_implementation false [get_files C:/Users/msa.azzazy.AUC/single_cycle/single_cycle.srcs/constrs_1/new/rca_consts.xdc]


synth_design -top RCA_Demo -part xc7a100tcsg324-1


write_checkpoint -force -noxdef RCA_Demo.dcp

catch { report_utilization -file RCA_Demo_utilization_synth.rpt -pb RCA_Demo_utilization_synth.pb }
