set_property PACKAGE_PIN J17 [get_ports {Anode[0]}]
set_property PACKAGE_PIN J18 [get_ports {Anode[1]}]
set_property PACKAGE_PIN T9 [get_ports {Anode[2]}]
set_property PACKAGE_PIN J14 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode[0]}]

set_property PACKAGE_PIN T10 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN R10 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN K13 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN P15 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN T11 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {LED_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]

set_property PACKAGE_PIN J15 [get_ports {A[0]}]
set_property PACKAGE_PIN L16 [get_ports {A[1]}]
set_property PACKAGE_PIN M13 [get_ports {A[2]}]
set_property PACKAGE_PIN R15 [get_ports {A[3]}]
set_property PACKAGE_PIN R17 [get_ports {A[4]}]
set_property PACKAGE_PIN T18 [get_ports {A[5]}]
set_property PACKAGE_PIN U18 [get_ports {A[6]}]
set_property PACKAGE_PIN R13 [get_ports {A[7]}]

set_property PACKAGE_PIN T8 [get_ports {B[0]}]
set_property PACKAGE_PIN U8 [get_ports {B[1]}]
set_property PACKAGE_PIN R16 [get_ports {B[2]}]
set_property PACKAGE_PIN T13 [get_ports {B[3]}]
set_property PACKAGE_PIN H6 [get_ports {B[4]}]
set_property PACKAGE_PIN U12 [get_ports {B[5]}]
set_property PACKAGE_PIN U11 [get_ports {B[6]}]
set_property PACKAGE_PIN V10 [get_ports {B[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {A[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {B[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]

set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]